---
- hosts: nodes
  tasks:
   - name: Install git
     apt:
       name: git
       state: present
   
   - name: Add Java repository
     apt_repository: repo='ppa:webupd8team/java' state=present update_cache=yes 
     become: true
   
   - name: update
     apt:
       update_cache: yes

   - name: Add license for java
     debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value=true vtype=select
     become: true

   - name: Install java
     apt: name={{item}} state=present
     with_items:
      - oracle-java8-installer
      - oracle-java8-set-default
     become: true

   - name: Install ca-certificates
     apt: name=ca-certificates state=present
     become: true
    
   - name: Install additional packages
     apt:
       name: "{{item}}"
       state: present
     with_items:
      - nginx
      - npm
      - mongodb
      - nodejs
      - python-pip
      - maven
   
   - name: Install pymongo
     pip: name=pymongo state=present
     
   #- name: Add users to mongodb database
     #mongodb_user:
       #login_host=127.0.0.1
       #database: admin
       #name: admin
       #password: pass123
       #login_port:8080
       #roles: readWrite,dbAdmin
       #state: present
   
   - name: To check if git is already cloned
     stat: path= /home/vagrant/checkbox.io
     register: temp
     
   - name: Download git repo
     command: git clone https://github.com/vishalkumarsa/checkbox.io
     when: not temp.stat.exists
    
   - name: npm install step
     npm: path=/home/vagrant/checkbox.io/server-side/site
     register: npm_complete
     become: yes
       
   - name: pwd
     command: node -v
     register: output
    
   - name: debug
     debug:
       msg: "{{output.stdout}}"
   
   - name: Configure nginx defaults 
     copy:
       src: /home/vagrant/checkbox.io/local-conf/default
       dest: /etc/nginx/sites-available/default
       force: yes
       remote_src: True
     #when: first_run|changed 

   - name: configure nginx conf
     copy:
       src: /home/vagrant/checkbox.io/local-conf/nginx.conf
       dest: /etc/nginx/nginx.conf
       force: yes
       remote_src: True
     #when: first_run|changed
    
   - name: Service nginx restart
     service: name=nginx state=restarted
   
   - name: node
     shell: chdir=/home/vagrant/checkbox.io/server-side/site node server.js
     environment:
       MONGO_PORT: 8080
       MONGO_IP: 127.0.0.1 
       MONGO_USER: mongo
       MONGO_PASSWORD: mongo        
       MAIL_USER: mail
       MAIL_PASSWORD: mail
       MAIL_SMTP: 127.0.0.1:8082
  
        
    
