---
- hosts: localhost
  connection: local
  serial: 1
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:  
    - include: tasks/droplet.yml



- hosts: newdroplets
  user: jenkins      
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/software.yml
               

